services:

  nginx:
    image: nginx:1.19.0
    ports:
      - "80:80"
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    networks:
      - web_network

  wordpress1:
    image: wordpress:5.4.2-php7.2-apache
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress1:/var/www/html
    networks:
      - web_network
  
  wordpress2:
    image: wordpress:5.4.2-php7.2-apache
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress2:/var/www/html
    networks:
      - web_network

  wordpress3:
    image: wordpress:5.4.2-php7.2-apache
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress3:/var/www/html
    networks:
      - web_network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    networks:
      - web_network

networks:
  web_network:
    driver: overlay

